stages:
  - build
  - deploy

build_ios_staging:
  dependencies: []
  stage: build
  before_script:
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US:en
    - rbenv local 2.7.5
    - bundle install
    - bundle update fastlane
  script:
    - yarn
    - cd ios; pod deintegrate; pod install; cd ..
    - bundle exec fastlane build_proj buildType:staging platform:ios
  tags:
    - ios
  only:
    - merge_requests
  when: manual

build_android_staging:
  image: reactnativecommunity/react-native-android:latest
  dependencies: []
  stage: build
  before_script:
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US:en
    - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
    - chmod +x ./android/gradlew
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - bundle install --gemfile=Gemfile.android
    - bundle update fastlane --gemfile=Gemfile.android
  cache:
    key: bh
    paths:
      - ./node_modules
      - .gradle/wrapper
      - .gradle/caches
  script:
    - yarn
    - npx jetify
    - bundle exec fastlane build_proj buildType:staging platform:android
  tags:
    - android
  only:
    - merge_requests
  when: manual

deploy_android_staging:
  image: reactnativecommunity/react-native-android:latest
  dependencies: []
  stage: deploy
  before_script:
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US:en
    - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
    - chmod +x ./android/gradlew
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - bundle install --gemfile=Gemfile.android
    - bundle update fastlane --gemfile=Gemfile.android
  cache:
    key: bh
    paths:
      - ./node_modules
      - .gradle/wrapper
      - .gradle/caches
  script:
    - yarn
    - npx jetify
    - fastlane deploy buildType:staging platform:android
  tags:
    - android
  only:
    - develop
  when: manual

deploy_ios_staging:
  dependencies: []
  stage: deploy
  before_script:
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US:en
    - rbenv local 2.7.5
    - bundle install --path ~/.gem
    - bundle update fastlane
  script:
    - yarn
    - cd ios; pod deintegrate; pod install; cd ..
    - bundle exec fastlane deploy buildType:staging platform:ios
  tags:
    - ios
  only:
    - develop
  when: manual
