stages:
  - build_deploy

before_script:
  - yarn
  - apk add --no-cache bash git curl jq
  - npm install -g firebase-tools

variables:
  EXPO_TOKEN: $EXPO_TOKEN

image: node:alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .yarn

# Base job template for building and deploying
.build-deploy-job: &build_deploy_job
  stage: build_deploy
  script:
     - npx eas-cli build --platform $PLATFORM --profile $PROFILE --non-interactive
  when: manual

android_firebase_staging:
  <<: *build_deploy_job
  variables:
    PLATFORM: "android"
    PROFILE: "previewStaging"
    FIREBASE_APP_ID: $FIREBASE_STAGING_APP_ID_ANDROID

android_firebase_production:
  <<: *build_deploy_job
  variables:
    PLATFORM: "android"
    PROFILE: "previewProduction"
    FIREBASE_APP_ID: $FIREBASE_PRODUCTION_APP_ID_ANDROID

ios_firebase_staging:
  <<: *build_deploy_job
  variables:
    PLATFORM: "ios"
    PROFILE: "previewStaging"
    FIREBASE_APP_ID: $FIREBASE_STAGING_APP_ID_IOS

ios_firebase_production:
  <<: *build_deploy_job
  variables:
    PLATFORM: "ios"
    PROFILE: "previewProduction"
    FIREBASE_APP_ID: $FIREBASE_PRODUCTION_APP_ID_IOS

ios_testflight:
  stage: build_deploy
  script:
    # Build iOS and submit IPA
    - npx eas-cli build --platform ios --profile production --auto-submit --latest --non-interactive
  when: manual


android_google_play:
  stage: build_deploy
  script:
    # Build iOS and submit apk
    - npx eas-cli build --platform android --profile production --auto-submit --latest --non-interactive
  when: manual

